# Dataframe df

Un dataframe va ser un conjunto de series(Listas []). Nos apoyamos de los diccionarios

In [11]:
diccionario_ventas = {
    "id_venta": [101,102,103],
    "cliente": ["Ana","Luis","Carlos"],
    "monto": [150.50,300.00,85.00]
}

In [2]:
diccionario_ventas

{'id_venta': [101, 102, 103],
 'cliente': ['Ana', 'Luis', 'Carlos'],
 'monto': [150.5, 300.0, 85.0]}

In [4]:
#pip install pandas
import pandas as pd

In [6]:
#Convertir el diccionario en un Dataframe (Tabla de Excel)
df_ventas = pd.DataFrame(diccionario_ventas)

In [9]:
print("Nuesta primera tabla en Pandas:")
display(df_ventas)

Nuesta primera tabla en Pandas:

   id_venta cliente  monto
0       101     Ana  150.5
1       102    Luis  300.0
2       103  Carlos   85.0

In [12]:
pd.DataFrame({
    "id_venta": [101,102,103],
    "cliente": ["Ana","Luis","Carlos"],
    "monto": [150.50,300.00,85.00]
})

   id_venta cliente  monto
0       101     Ana  150.5
1       102    Luis  300.0
2       103  Carlos   85.0

# Leer Archivos con Pandas

In [13]:
#1. La ubicacion del archivo
url_archivo = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
#2. Leer el archivo, y asignarlo (encapsular) en una variable df
df_archivo = pd.read_csv(url_archivo) # delimitador por defecto es la coma ",", por defecto considera que la primera fila del csv es el header
#3. Mostramos la informacion
print("Informacion del archivo:")
display(df_archivo)

Informacion del archivo:

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [18]:
#import pandas as pd
#Desde el escritorio
#url_archivo_escritorio = "C:\Users\xp75713\Downloads\Examen_AWS_Condori\Data\ventas.csv"
#En el colab
url_archivo_colab = "/content/Data/ventas_coma.csv"

df_ventas = pd.read_csv(url_archivo_colab, sep=",")
display(df_ventas)

   id_venta       fecha cliente  monto
0         1  2026-06-01     Ana  150.5
1         2  2026-06-02    Luis  200.0
2         3  2026-06-02  Carlos   99.9
3         4  2026-06-01     Ana  150.5
4         5  2026-06-02    Luis  200.0
5         6  2026-06-02  Carlos   99.9
6         7  2026-06-01     Ana  150.5
7         8  2026-06-02    Luis  200.0
8         9  2026-06-02  Carlos   99.9

In [21]:
#En el colab
url_archivo_colab_rrhh = "/content/Data/rrhh_sucio_punto_coma.csv"

#Leer el archivo
df_rrhh = pd.read_csv(url_archivo_colab_rrhh, sep=";",skiprows=2)

#Mostrar el archivo
display(df_rrhh)

  id_empleado nombre departamento  salario
0        E001  Maria       Ventas     4500
1        E002   Juan           IT     5200
2        E003  Pedro    Marketing     3800

In [24]:
#En el colab
url_archivo_colab_lg = "/content/Data/logistica_palote.csv"

columnas_utiles = ["guia","peso_kg","estado"]
valores_basura = ["???", "No_Data"]

#Leer el archivo
df_lg = pd.read_csv(
    url_archivo_colab_lg,
    sep="|",
    usecols=columnas_utiles,
    na_values=valores_basura
    )

#Mostrar el archivo
display(df_lg)

   guia  peso_kg       estado
0  G100     15.5    Entregado
1  G101      NaN  En transito
2  G102     22.0          NaN
3  G103      8.5    Entregado

In [25]:
#En el colab
url_archivo_colab_lg = "/content/Data/logistica_palote.txt"

columnas_utiles = ["guia","peso_kg","estado"]
valores_basura = ["???", "No_Data"]

#Leer el archivo
df_lg = pd.read_csv(
    url_archivo_colab_lg,
    sep="|",
    usecols=columnas_utiles,
    na_values=valores_basura
    )

#Mostrar el archivo
display(df_lg)

   guia  peso_kg       estado
0  G100     15.5    Entregado
1  G101      NaN  En transito
2  G102     22.0          NaN
3  G103      8.5    Entregado

In [26]:
#!pip install openpyxl
#En el colab
url_archivo_colab_rf = "/content/Data/reporte_financiero_excel.xlsx"

##Leer el archivo:
#Ingresos
df_rf_ingresos = pd.read_excel(url_archivo_colab_rf) # Por defecto lee la primera hoja
#Gastos
df_rf_gastos = pd.read_excel(url_archivo_colab_rf, sheet_name="Gastos_2026") # Por defecto lee la primera hoja

#Mostrar el archivo
display(df_rf_ingresos)
display(df_rf_gastos)

  Factura      Fecha    Cliente  Monto
0   F-001 2026-06-01  Empresa A   5000
1   F-002 2026-06-05  Empresa B   7500

  Recibo    Categoria         Descripcion  Total
0   R-10  Operaciones  Pago de Servidores   1200
1   R-11    Marketing      Publicidad Web    800

In [27]:
# Cuando realizas la lectura de un archivo plano o 2D, el tipo de dato siempre sera string (cadena de texto) Type: Object
data_cruda = {
    "id_transaccion": ["001", "002", "003", "003"],
    "fecha_compra": ["2026-01-15", "2026/02/20", "2026-03-10", "2026-03-10"],
    "cliente": ["  Ana Perez ", "luis gomez", "CARLOS RUIZ", "CARLOS RUIZ"],
    "monto_usd": ["150.50", "200.00", "No Data", "No Data"]
}

df_etl = pd.DataFrame(data_cruda)

In [28]:
df_etl.dtypes

id_transaccion    object
fecha_compra      object
cliente           object
monto_usd         object
dtype: object

In [29]:
pd.DataFrame(data_cruda).dtypes

id_transaccion    object
fecha_compra      object
cliente           object
monto_usd         object
dtype: object

In [30]:
#import pandas as pd
#Desde el escritorio
#url_archivo_escritorio = "C:\Users\xp75713\Downloads\Examen_AWS_Condori\Data\ventas.csv"
#En el colab
url_archivo_colab = "/content/Data/ventas_coma.csv"

df_ventas = pd.read_csv(url_archivo_colab, sep=",")
display(df_ventas)

   id_venta       fecha cliente  monto
0         1  2026-06-01     Ana  150.5
1         2  2026-06-02    Luis  200.0
2         3  2026-06-02  Carlos   99.9
3         4  2026-06-01     Ana  150.5
4         5  2026-06-02    Luis  200.0
5         6  2026-06-02  Carlos   99.9
6         7  2026-06-01     Ana  150.5
7         8  2026-06-02    Luis  200.0
8         9  2026-06-02  Carlos   99.9

In [33]:
#Controlar el error al momento de castear, se usa el parametro errors = 'coerce' para volver el valor en null (NaN)
#pd.to_datetime(df_ventas["fecha"], errors='coerce')

#Tener un Backup
df_ventas_backup = df_ventas.copy()
df_ventas_backup = df_ventas_backup.copy()

#Update a una columna
df_ventas["fecha"] = pd.to_datetime(df_ventas["fecha"], errors='coerce')
display(df_ventas)

   id_venta      fecha cliente  monto
0         1 2026-06-01     Ana  150.5
1         2 2026-06-02    Luis  200.0
2         3 2026-06-02  Carlos   99.9
3         4 2026-06-01     Ana  150.5
4         5 2026-06-02    Luis  200.0
5         6 2026-06-02  Carlos   99.9
6         7 2026-06-01     Ana  150.5
7         8 2026-06-02    Luis  200.0
8         9 2026-06-02  Carlos   99.9

In [34]:
df_ventas.dtypes

id_venta             int64
fecha       datetime64[ns]
cliente             object
monto              float64
dtype: object

In [41]:
#Agregar columnas
df_ventas["mes_venta"] = df_ventas["fecha"].dt.month
df_ventas["dia_semana"] = df_ventas["fecha"].dt.day_name()
df_ventas["anio"] = df_ventas["fecha"].dt.year

In [42]:
display(df_ventas)

   id_venta      fecha cliente  monto  mes_venta dia_semana  anio
0         1 2026-06-01     Ana  150.5          6     Monday  2026
1         2 2026-06-02    Luis  200.0          6    Tuesday  2026
2         3 2026-06-02  Carlos   99.9          6    Tuesday  2026
3         4 2026-06-01     Ana  150.5          6     Monday  2026
4         5 2026-06-02    Luis  200.0          6    Tuesday  2026
5         6 2026-06-02  Carlos   99.9          6    Tuesday  2026
6         7 2026-06-01     Ana  150.5          6     Monday  2026
7         8 2026-06-02    Luis  200.0          6    Tuesday  2026
8         9 2026-06-02  Carlos   99.9          6    Tuesday  2026

In [43]:
#En el colab
url_archivo_colab_lg = "/content/Data/logistica_palote.txt"

#Leer el archivo
df_lg = pd.read_csv(
    url_archivo_colab_lg,
    sep="|"
    )

#Mostrar el archivo
display(df_lg)

   guia    origen   destino peso_kg       estado
0  G100      Lima  Arequipa    15.5    Entregado
1  G101     Cusco      Lima     ???  En transito
2  G102     Piura     Tacna    22.0      No_Data
3  G103  Trujillo      Lima     8.5    Entregado

In [44]:
df_lg.dtypes

guia       object
origen     object
destino    object
peso_kg    object
estado     object
dtype: object

In [46]:
df_lg["peso_kg"] = pd.to_numeric(df_lg["peso_kg"], errors="coerce")

In [47]:
display(df_lg)

   guia    origen   destino  peso_kg       estado
0  G100      Lima  Arequipa     15.5    Entregado
1  G101     Cusco      Lima      NaN  En transito
2  G102     Piura     Tacna     22.0      No_Data
3  G103  Trujillo      Lima      8.5    Entregado

In [48]:
# Imputacion de datos
# ¿Que hacemos con los nulos? Vamos a rellenarlo con el promedio de la serie
promedio_peso = df_lg["peso_kg"].mean()
print(promedio_peso)
df_lg["peso_kg"] = df_lg["peso_kg"].fillna(promedio_peso)

15.333333333333334

In [49]:
display(df_lg)

   guia    origen   destino    peso_kg       estado
0  G100      Lima  Arequipa  15.500000    Entregado
1  G101     Cusco      Lima  15.333333  En transito
2  G102     Piura     Tacna  22.000000      No_Data
3  G103  Trujillo      Lima   8.500000    Entregado

In [52]:
# ¿Como reemplazamos un dato en una serie? Utilizamos el replace
#Se imputa como entregado debido a que el area comercial indica que es por ...
data_imputar = "Entregado"

df_lg['estado'] = df_lg['estado'].replace("N/D",data_imputar)
display(df_lg)

   guia    origen   destino    peso_kg       estado
0  G100      Lima  Arequipa  15.500000    ENTREGADO
1  G101     Cusco      Lima  15.333333  EN TRANSITO
2  G102     Piura     Tacna  22.000000    Entregado
3  G103  Trujillo      Lima   8.500000    ENTREGADO

In [54]:
df_lg['estado'] = df_lg['estado'].str.lower()
display(df_lg)

   guia    origen   destino    peso_kg       estado
0  G100      Lima  Arequipa  15.500000    entregado
1  G101     Cusco      Lima  15.333333  en transito
2  G102     Piura     Tacna  22.000000    entregado
3  G103  Trujillo      Lima   8.500000    entregado

In [55]:
#En el colab
url_archivo_colab_rrhh = "/content/Data/rrhh_sucio_punto_coma.csv"

#Leer el archivo
df_rrhh = pd.read_csv(url_archivo_colab_rrhh, sep=";",skiprows=2)

#Mostrar el archivo
display(df_rrhh)

  id_empleado nombre departamento  salario
0        E001  Maria       Ventas     4500
1        E002   Juan           IT     5200
2        E003  Pedro    Marketing     3800

In [56]:
#import numpy as np

In [58]:
df_rrhh['bono_asignado'] = np.where( df_rrhh['departamento'] == "IT", #Condicion
         df_rrhh['salario']*0.10,          #En caso sea true
         0                                 #En caso sea false
)
display(df_rrhh)

  id_empleado nombre departamento  salario  bono_asignado
0        E001  Maria       Ventas     4500            0.0
1        E002   Juan           IT     5200          520.0
2        E003  Pedro    Marketing     3800            0.0

In [59]:
df_rrhh["sueldo_final"] = df_rrhh["salario"] + df_rrhh["bono_asignado"]
display(df_rrhh)

  id_empleado nombre departamento  salario  bono_asignado  sueldo_final
0        E001  Maria       Ventas     4500            0.0        4500.0
1        E002   Juan           IT     5200          520.0        5720.0
2        E003  Pedro    Marketing     3800            0.0        3800.0