# Limpieza - Eliminación de duplicados

In [1]:
import pandas as pd

In [2]:
df_ventas =  pd.DataFrame({
    "id_venta": [101,102,102,103],
    "monto": [50.0,120.0,120.0,85.0]
})
display(df_ventas)

   id_venta  monto
0       101   50.0
1       102  120.0
2       102  120.0
3       103   85.0

In [3]:
df_ventas.drop_duplicates(inplace=True)
display(df_ventas)

   id_venta  monto
0       101   50.0
1       102  120.0
3       103   85.0

In [4]:
df_pagos = pd.DataFrame({
    "id_pago": ["P101","P102","P102"],
    "estado": ["Pagado","Pendiente","Pagado"]
})

display(df_pagos)

  id_pago     estado
0    P101     Pagado
1    P102  Pendiente
2    P102     Pagado

In [5]:
df_pagos.drop_duplicates(subset=["id_pago"], keep="last",inplace=True)
display(df_pagos)

  id_pago  estado
0    P101  Pagado
2    P102  Pagado

#Manipulacion de strings

In [11]:
df_clientes = pd.DataFrame({
    "ciudad": ["  LIMA ", "cusco", "AreQuiPa","Lima"]
})

In [12]:
df_clientes["ciudad_standar"] = df_clientes["ciudad"].str.strip().str.title()

In [13]:
display(df_clientes)

     ciudad ciudad_standar
0     LIMA            Lima
1     cusco          Cusco
2  AreQuiPa       Arequipa
3      Lima           Lima

In [14]:
df_telefonos = pd.DataFrame({"celular": ["+51 987-654", "(01) 456-789"]})

In [15]:
df_telefonos["celular_limpio"] = (df_telefonos["celular"]
                                  .str.replace("-","")
                                  .str.replace(" ","")
                                  .str.replace("+51","")
                                  .str.replace("(01)",""))

In [16]:
display(df_telefonos)

        celular celular_limpio
0   +51 987-654         987654
1  (01) 456-789         456789

In [ ]:
df_productos = pd.DataFrame({
    "precio_sin_igv": [100.0,50.0,200.0]
})

#Precio Final va ser con igv
df_productos["precio_final"] = df_productos["precio_sin_igv"].apply(lambda x: x * 1.18)

In [18]:
display(df_productos)

   precio_sin_igv
0           100.0
1            50.0
2           200.0

In [21]:
df_inv = pd.DataFrame({"codigo_caja": [" CAJA-101-A ", "CAJA-102-B  ", "  CAJA-103-C"]})

In [ ]:
df_inv["codigo_caja_limpio"] = df_inv["codigo_caja"].str.strip().str.split("-")[1]

In [23]:
df_inv["id_caja"] = df_inv["codigo_caja"].apply(lambda x: x.strip().split("-")[1])

In [24]:
display(df_inv)

    codigo_caja id_caja
0   CAJA-101-A      101
1  CAJA-102-B       102
2    CAJA-103-C     103

In [26]:
df_empleados = pd.DataFrame({
    "salario_txt": ["S/. 4500", "USD 1200", "Sin Dato", "S/. 3200"]})

In [25]:
def limpiar_salario(salario_txt):
    if "S/. " in salario_txt:
        salario = salario_txt.replace("S/. ","")
        return float(salario)
    elif "USD" in salario_txt:
        salario = salario_txt.replace("USD ","")
        return float(salario) * 3.5
    else:
        return 0.0

In [29]:
df_empleados["salario_float"] = df_empleados["salario_txt"].apply(limpiar_salario)

In [30]:
df_empleados

  salario_txt  salario_float
0    S/. 4500         4500.0
1    USD 1200         4200.0
2    Sin Dato            0.0
3    S/. 3200         3200.0

In [31]:
df_ventas_regionales = pd.DataFrame({
    "ciudad": ["Lima", "Cusco", "Lima", "Arequipa"],
    "monto": [150.0, 200.0, 50.0, 300.0]
})

In [36]:
def calcular_comision(fila):
  ciudad = fila["ciudad"]
  monto = fila["monto"]

  if ciudad == "Lima":
    return monto * 0.1
  elif ciudad != "Lima":
    return monto * 0.05

In [37]:
df_ventas_regionales["comision"] = df_ventas_regionales.apply(calcular_comision, axis=1)

In [38]:
df_ventas_regionales

     ciudad  monto  comision
0      Lima  150.0      15.0
1     Cusco  200.0      10.0
2      Lima   50.0       5.0
3  Arequipa  300.0      15.0

In [39]:
df_enero = pd.DataFrame({"id": [1, 2], "monto": [100, 200]})
df_febrero = pd.DataFrame({"id": [3, 4], "monto": [300, 400]})

In [40]:
df_enero

   id  monto
0   1    100
1   2    200

In [41]:
df_febrero

   id  monto
0   3    300
1   4    400

In [42]:
df_historico = pd.concat([df_enero, df_febrero], ignore_index=True)

In [43]:
df_historico

   id  monto
0   1    100
1   2    200
2   3    300
3   4    400

In [46]:
# Simulamos dos tablas
df_clientes = pd.DataFrame({
    "id_cliente": [1, 2, 3],
    "nombre": ["Ana", "Luis", "Carlos"]
})

df_ventas = pd.DataFrame({
    "id_cliente": [1, 2, 4], # Nota: No hay venta del cliente 3, y el 4 es un cliente fantasma
    "monto": [500, 300, 900]
})

# 1. INNER JOIN (La Intersección estricta)
# Solo trae los que hacen 'Match' perfecto en ambas tablas (Clientes 1 y 2)
df_inner = pd.merge(df_clientes, df_ventas, on="id_cliente", how="inner")

# 2. LEFT JOIN (Manda la Izquierda)
# Trae TODOS los clientes. Si no tienen venta, Pandas les pondrá NaN (Cliente 3)
df_left = pd.merge(df_clientes, df_ventas, on="id_cliente", how="left")

# 3. RIGHT JOIN (Manda la Derecha)
# Trae TODAS las ventas. Si la venta no tiene cliente registrado, le pone NaN (Cliente 4)
df_right = pd.merge(df_clientes, df_ventas, on="id_cliente", how="right")

# 4. OUTER JOIN (El Todo Incluido)
# Trae a TODOS, crucen o no crucen. (Clientes 1, 2, 3 y 4)
df_outer = pd.merge(df_clientes, df_ventas, on="id_cliente", how="outer")

print("Ejemplo de INNER JOIN (La Intersección estricta):")
display(df_inner)
print("Ejemplo de LEFT JOIN (Manda la Izquierda):")
display(df_left)
print("Ejemplo de RIGTH JOIN (Manda la Derecha):")
display(df_right)
print("Ejemplo de OUTER JOIN (El Todo Incluido):")
display(df_outer)

Ejemplo de INNER JOIN (La Intersección estricta):

   id_cliente nombre  monto
0           1    Ana    500
1           2   Luis    300

Ejemplo de LEFT JOIN (Manda la Izquierda):

   id_cliente  nombre  monto
0           1     Ana  500.0
1           2    Luis  300.0
2           3  Carlos    NaN

Ejemplo de RIGTH JOIN (Manda la Derecha):

   id_cliente nombre  monto
0           1    Ana    500
1           2   Luis    300
2           4    NaN    900

Ejemplo de OUTER JOIN (El Todo Incluido):

   id_cliente  nombre  monto
0           1     Ana  500.0
1           2    Luis  300.0
2           3  Carlos    NaN
3           4     NaN  900.0